---
- name: "Install logwatch package"
  ansible.builtin.apt:
    name:
      - logwatch
    state: present
    update_cache: true

- name: "Configure Logwatch"
  ansible.builtin.template:
    src: logwatch.conf.j2
    dest: /etc/logwatch/conf/logwatch.conf
    owner: root
    group: root
    mode: '0644'
