# tasks for nftables using template

- name: Install nftables
  ansible.builtin.apt:
    name: nftables
    state: present

- name: Deploy nftables configuration from template
  ansible.builtin.template:
    src: nftables.conf.j2
    dest: /etc/nftables.conf
    owner: root
    group: root
    mode: '0750'
  notify: Reload NFTables

- name: Enable and start nftables service
  ansible.builtin.systemd:
    name: nftables
    enabled: true
    state: started
